version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:573bf041ce0f1f95bab8f781b153de2c01ffb851c736d8ee899fdcaeedb4e4b8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
