version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:4f30221be2736b5bf3974c40825d15ffc805dda5aedc8c743ae294e1b33b6059
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
