version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:e34d13c06846de2fc68774943e161c8056dedaf286b855bba1852e55c115628c
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: dist
