version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:132a60375ddf66bb5d039f68accd7b641ac1a17020208579d0a9a18be2ff613b
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
