version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:00fff2d7c54ae6172cf5a343124cf7b2ea1aaa4f98168b306a6877ad8e5140e8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
