version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:d6b14ac4d893765ecc27d18e1181d0e57cccc0b4d8b0510223eafd8045597b82
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
