version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:86713b1c8f246f66c8e734ad38aa5ef876c4e47a69400f106c8e6db07559ea9f
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
