version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:774127d75444d6cdc760782ac1dc801a09afef241bb15256d0b5cad4daa1c8bc
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
