version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:c735aa694ecda7bfb0de9cc5a26d7bbb46b9e77f7565898d33203e080c9ed34b
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
