version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:35d5e9abfe5ebdd7434f5afec0b24fbfca10de2790750f9aad2e67d4a402b3cb
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
