version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:ead51e11614fbb219bdafb490798fca1d52feba921f57f978501c44abbbdcae2
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
