version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:38204319f673f8437a6f2d317599a988bae361c11ed2faf36e83d660f81620d8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run build
      - store_artifacts:
          path: packages/dist
