version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:7beec57354c670c3d6809b0981c9e0c469e1c29b0a979b1b1463498cbf044ff1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
