version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:7abbee33d979dba21ec62a5e2a3face4def1d6ffff5baf052d20d0d68c7e6001
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
