version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:9d7b5a830759fc5413f94cdd8d4bbe0a245ea513dd608580a06d58c2a7c45c6e
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: packages/dist
