version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers@sha256:d5d6fb871912b6fe22d086ceb43b2650dcfcc395d8785abcb29fc8dc6259f4cc
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: npm run build
      - store_artifacts:
          path: dist
